name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php:
          - 8.1
          - 8.2
        stability:
          - prefer-lowest
          - prefer-stable

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate Composer
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "cache=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Restore Composer Cache
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.composer-cache.outputs.cache }}
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.stability }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.stability }}-composer

      - name: Install Dependencies
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Static analysis
        run: vendor/bin/psalm --no-cache --shepherd

      - name: Execute tests
        run: vendor/bin/pest
